### ISSUE TITLE
What is this path?

### ISSUE THREAD

**Issue by wangzhe112-lab** [ytyz1307zzh/PLUG#1]
![image](https://github.com/user-attachments/assets/fa629c6c-6b7f-40f2-8d6f-d607fd4e9925)

Congratulations on the successful publication of your paper. I would like to ask you what this path means? I don't quite understand.

**Comment by ytyz1307zzh** [comment]
Oh sorry for the confusion. I used a text file to save my Huggingface token, and the script reads the token to log in to huggingface. Some models like Llama require a log in before they can be downloaded. Feel free to your preferred login method such as `huggingface-cli login` from the command line or using the environment variable `HF_TOKEN`. more details can be found at https://huggingface.co/docs/huggingface_hub/en/quick-start.

**Comment by wangzhe112-lab** [comment]
Thank you very much for your answer.
